// ============================================
// SPELLS-DATA.JS — All spells, all schools
// ============================================

window.SPELLS = {
  lux: [
    {
      name: "Ward of the Perimeter",
      school: "lux",
      mapping: "Firewall / WAF configuration",
      rating: "built",
      desc: "A shimmering boundary of light, cast at the edge of all things. No packet passes uninspected. The first line, the eternal wall.",
    },
    {
      name: "Shield of Zero Trust",
      school: "lux",
      mapping: "Zero Trust Architecture",
      rating: "built",
      desc: "Trust is poison. The shield recognizes this truth. Every soul, every process, every request must prove itself worthy — always. No exceptions. No inheritance.",
    },
    {
      name: "Sanctum Seal",
      school: "lux",
      mapping: "Data encryption at rest (AES-256)",
      rating: "built",
      desc: "What rests in the vault is wrapped in 256 layers of light. The seal is ancient, mathematical, unbreakable to all but the holder of the key.",
    },
    {
      name: "Veil of Transit",
      school: "lux",
      mapping: "Encryption in transit (TLS/mTLS)",
      rating: "built",
      desc: "As secrets travel between worlds, the Veil wraps them in light invisible to the watching eye. Man-in-the-middle sees only shimmer.",
    },
    {
      name: "Beacon of Anomaly",
      school: "lux",
      mapping: "SIEM / anomaly detection",
      rating: "built",
      desc: "In the dark, the Beacon watches. It knows what normal looks like. When the pattern breaks — even by a hair — it screams.",
    },
    {
      name: "Restoration Rite",
      school: "lux",
      mapping: "Backup & disaster recovery",
      rating: "built",
      desc: "All things end. The Restoration Rite is the prayer spoken after catastrophe — the spell that reaches into backup and pulls reality back from ash.",
    },
    {
      name: "Circle of Least Privilege",
      school: "lux",
      mapping: "IAM / principle of least privilege",
      rating: "built",
      desc: "Draw the circle tight. Grant only what is needed. The greatest breaches begin where permissions grew fat and lazy.",
    },
    {
      name: "Mirror of Deception",
      school: "lux",
      mapping: "Honeypots / deception technology",
      rating: "built",
      desc: "A perfect replica. Irresistible. The attacker reaches for the prize and finds — the mirror's gaze. You watched them the whole time.",
    },
    {
      name: "Glyph of Authentication",
      school: "lux",
      mapping: "Multi-factor authentication",
      rating: "built",
      desc: "One key is never enough. The Glyph demands something you know, something you hold, something you are. The trinity of proof.",
    },
    {
      name: "Aura of Compliance",
      school: "lux",
      mapping: "Compliance frameworks (SOC2, ISO27001)",
      rating: "built",
      desc: "The golden aura that tells the world: we have been tested. We have been measured. We did not break.",
    },
    {
      name: "Chrono Seal",
      school: "lux",
      mapping: "Immutable audit logs / write-once storage",
      rating: "built",
      desc: "Time itself is written and locked. No one may alter the past. Every action preserved in amber, waiting for the day it must bear witness.",
    },
    {
      name: "Whisper Net",
      school: "lux",
      mapping: "Encrypted internal comms / zero-knowledge channels",
      rating: "buildable",
      desc: "Even within the sanctum, the walls may have ears. The Whisper Net ensures what passes between allies cannot be understood by the walls themselves.",
    },
    {
      name: "Purification Rite",
      school: "lux",
      mapping: "Input sanitization / data validation",
      rating: "built",
      desc: "What enters the system must be cleansed. SQL and script and shell code — all poisons dressed as offerings. The Rite burns them clean.",
    },
  ],
  shadow: [
    {
      name: "Shadow Walk",
      school: "shadow",
      mapping: "Penetration testing / red team ops",
      rating: "built",
      desc: "To know your enemy, become your enemy. The Shadow Walk sends you through your own walls as an attacker. What you find there is the truth no compliance framework will tell you.",
    },
    {
      name: "Hex Trace",
      school: "shadow",
      mapping: "Data exfiltration detection",
      rating: "buildable",
      desc: "Data leaving without permission leaves a hex. The Trace follows the residue of stolen secrets, backwards through the dark, to the source.",
    },
    {
      name: "Curse Reversal",
      school: "shadow",
      mapping: "Incident response & containment",
      rating: "built",
      desc: "The breach is real. The damage spreads. The Curse Reversal is the ritual of triage — contain, eradicate, recover, learn. Performed under fire.",
    },
    {
      name: "Phantom Hunt",
      school: "shadow",
      mapping: "Proactive threat hunting",
      rating: "buildable",
      desc: "Some threats do not announce themselves. They breathe quietly inside your systems, patient as stones. The Phantom Hunt seeks them by intuition, by pattern, by a hunter's sixth sense.",
    },
    {
      name: "Void Gaze",
      school: "shadow",
      mapping: "Dark web monitoring / OSINT",
      rating: "built",
      desc: "Stare into the void — and read it. Your stolen credentials, your leaked source code, your exposed architecture — it's all visible to those who know how to look.",
    },
    {
      name: "Soul Bind",
      school: "shadow",
      mapping: "Digital forensics / chain of custody",
      rating: "built",
      desc: "The evidence must remain pure. The Soul Bind preserves the chain — every artifact, every timestamp, every bit — immutable, admissible, true.",
    },
    {
      name: "Necromancy of Dead Process",
      school: "shadow",
      mapping: "Memory forensics / volatile data recovery",
      rating: "buildable",
      desc: "What the attacker thought was gone — the process killed, the memory freed — can be called back. The Necromancer reads RAM like scripture.",
    },
    {
      name: "Poison Oracle",
      school: "shadow",
      mapping: "Threat intelligence feeds",
      rating: "built",
      desc: "The Oracle has drunk from a thousand poisoned wells and survived. Now it tells you which new poisons are being brewed and by whom.",
    },
    {
      name: "Eclipse Protocol",
      school: "shadow",
      mapping: "Kill switch / emergency network isolation",
      rating: "built",
      desc: "When all else fails — when the beast is inside the walls — you speak the Eclipse. Everything goes dark. The network severs. The bleeding stops.",
    },
    {
      name: "Serpent's Tongue",
      school: "shadow",
      mapping: "Social engineering assessment",
      rating: "buildable",
      desc: "The most sophisticated attack vector is the human. The Serpent speaks with trust, with authority, with urgency — and the employee holds open the door. Testing for this is the Serpent's Tongue spell.",
    },
    {
      name: "Blood Pact Audit",
      school: "shadow",
      mapping: "Supply chain security / vendor risk",
      rating: "built",
      desc: "Your vendor made a pact with you in blood — but what pacts did they make with others? The Blood Pact Audit traces every dependency, every third party, every upstream risk.",
    },
    {
      name: "Obsidian Eye",
      school: "shadow",
      mapping: "Continuous vulnerability scanning",
      rating: "built",
      desc: "An eye of volcanic black glass, never blinking, scanning the surface of every system for the crack that wasn't there yesterday.",
    },
    {
      name: "Wraith Trap",
      school: "shadow",
      mapping: "Advanced persistent threat (APT) detection",
      rating: "buildable",
      desc: "Nation-state actors move like wraiths — patient, methodical, nearly invisible. The Wraith Trap is set long before the attack. It waits for the small things: the unusual query, the off-hours login, the lateral movement.",
    },
  ],
  motus: [
    {
      name: "Shift of Shape",
      school: "motus",
      mapping: "Adaptive security posture management",
      rating: "buildable",
      desc: "The system learns the shape of its threat landscape and reshapes itself to meet it. Not static. Not predictable. Alive.",
    },
    {
      name: "Flow State",
      school: "motus",
      mapping: "SOAR / automated response orchestration",
      rating: "built",
      desc: "When the alerts cascade, the mage does not panic. Flow State routes each signal to the right responder, triggers the right playbook, coordinates without exhaustion.",
    },
    {
      name: "Temporal Sight",
      school: "motus",
      mapping: "Predictive threat modeling (AI)",
      rating: "buildable",
      desc: "The attack has not happened yet. But the pattern of what precedes attacks — in telemetry, in threat intel, in behavioral drift — these are visible to the Temporal Sight.",
    },
    {
      name: "Emergence Ward",
      school: "motus",
      mapping: "AI-driven autonomous defense",
      rating: "emerging",
      desc: "The ward that writes its own rules. When it encounters a new threat, it adapts without being told. The emergence is the ward growing beyond its initial programming.",
    },
    {
      name: "Pattern Weave",
      school: "motus",
      mapping: "Behavioral analytics / UEBA",
      rating: "built",
      desc: "Every user is a pattern. Every pattern, when disrupted, tells a story. The Weave catches the insider threat, the compromised credential, the zombie account — by the break in the rhythm.",
    },
    {
      name: "Cascade Break",
      school: "motus",
      mapping: "Circuit breaker patterns / blast radius limiting",
      rating: "buildable",
      desc: "When a system begins to fail, the failure seeks to spread. The Cascade Break is the self-sealing spell — it recognizes the cascade and severs the path before the whole falls.",
    },
    {
      name: "Evolution Sigil",
      school: "motus",
      mapping: "Self-healing systems / auto-patching",
      rating: "buildable",
      desc: "The Sigil burns itself into the system's skin. When a wound appears — a CVE, a misconfiguration, a regression — the Sigil heals it, silently, without human hands.",
    },
    {
      name: "Resonance Lock",
      school: "motus",
      mapping: "Signal correlation across telemetry",
      rating: "buildable",
      desc: "Every signal, across every source, every sensor, every log — the Resonance Lock finds the harmonics. The attack hiding across fifteen systems becomes one coherent song.",
    },
    {
      name: "Chaos Communion",
      school: "motus",
      mapping: "Chaos engineering / resilience testing",
      rating: "buildable",
      desc: "You call the chaos before the chaos calls you. Deliberately. Ritually. Inject failure into the living system and watch what survives. What doesn't survive — fix it.",
    },
    {
      name: "Living Grimoire",
      school: "motus",
      mapping: "Continuously learning threat knowledge base",
      rating: "buildable",
      desc: "The Grimoire updates itself. Every threat encountered, every IOC observed, every attack pattern dissected — written into the book. Next session, the mage already knows.",
    },
    {
      name: "Fractal Shield",
      school: "motus",
      mapping: "Defense-in-depth (each layer reflects the whole)",
      rating: "emerging",
      desc: "At every scale, the defense holds the same pattern. The firewall rule is the same philosophy as the kernel patch is the same philosophy as the employee policy. Fractal. Self-similar.",
    },
    {
      name: "Mycelium Network",
      school: "motus",
      mapping: "Zero-trust mesh / microsegmentation",
      rating: "emerging",
      desc: "Beneath the surface, a network of trust so granular it cannot be grasped whole — only traversed with the right credentials, the right context, the right moment. Like mycelium: invisible until it blooms.",
    },
    {
      name: "Outlier Sense",
      school: "motus",
      mapping: "Statistical anomaly detection / ML classifiers",
      rating: "buildable",
      desc: "In a field of a billion normal events, the Outlier Sense finds the one that doesn't belong. Statistical distance. Learned distributions. The smell of wrongness.",
    },
  ],
  wicked: [
    // Identity & Trust Crisis
    {
      name: "True Name Binding",
      school: "wicked",
      category: "Identity & Trust Crisis",
      mapping: "Decentralized identity, biometric fusion, behavioral biometrics, zero-knowledge proofs of identity",
      rating: "emerging",
      desc: "In a world of deepfakes, stolen credentials, and synthetic identities, how do you KNOW who someone is? This spell binds a true name to a soul — unforgeable, uncopiable, unarguable. The mathematics of identity made manifest.",
      analysis: "ZK-proofs of identity exist in labs. Biometric fusion is commercial. The gap: no universal standard binds them into one unforgeable identity layer. Closest active work: World ID (Worldcoin), Microsoft Entra Verified ID, W3C DIDs.",
      question: "If you could cast this spell: would you? What do you gain — and what do you give up?",
    },
    {
      name: "Memory of the Forgotten",
      school: "wicked",
      category: "Identity & Trust Crisis",
      mapping: "Passwordless auth, FIDO2/passkeys, distributed key management",
      rating: "buildable",
      desc: "Every human carries 100+ keys, most reused, most forgotten, most stolen. This spell remembers every key without storing them anywhere attackable. The vault that exists nowhere — yet opens everything.",
      analysis: "Passkeys/FIDO2 are HERE and deployed. Apple, Google, Microsoft all support them. The barrier is adoption. This spell is 80% cast — we just need the world to finish speaking it.",
      question: "Passkeys exist. Why haven't you switched? What would make you switch tomorrow?",
    },
    {
      name: "Oath of the Machine",
      school: "wicked",
      category: "Identity & Trust Crisis",
      mapping: "SPIFFE/SPIRE, machine identity management, workload attestation",
      rating: "buildable",
      desc: "Billions of devices, APIs, services — all need identities too. Cameras, sensors, microservices, satellites. This spell gives every machine a soul-signature — cryptographically unique, provably authentic, impossible to impersonate.",
      analysis: "SPIFFE/SPIRE is production-ready. Cloud providers offer managed machine identity. The challenge: the long tail of legacy IoT devices that were born without identity and can't be updated. Rough estimate: 15 billion devices currently identityless.",
      question: "If every device had a verified identity, what attacks become impossible — and what new attacks emerge?",
    },
    // The Human Vulnerability
    {
      name: "Mind Shield",
      school: "wicked",
      category: "The Human Vulnerability",
      mapping: "AI-powered phishing detection, deepfake detection, security awareness, cognitive firewalls",
      rating: "emerging",
      desc: "Deepfake CEOs on video calls. AI-generated phishing indistinguishable from real. The social engineering of the future is not a Nigerian prince — it is your mother's voice, your boss's face, your colleague's writing style. The Mind Shield makes humans immune to deception. Not by making them smarter. By making the deception visible.",
      analysis: "Deepfake detection exists but is in an arms race. AI-generated phishing detection is emerging (Google, Microsoft). The fundamental problem: humans are wired to trust faces and voices. Technical detection can help, but the real shield is cultural — verification protocols that make 'but it looked like you!' insufficient.",
      question: "When you can no longer trust your eyes and ears, what CAN you trust?",
    },
    {
      name: "The Unbreakable Oath",
      school: "wicked",
      category: "The Human Vulnerability",
      mapping: "Privacy-preserving insider threat detection, intent analysis, behavioral baselines",
      rating: "arcane",
      desc: "How do you prevent betrayal without treating everyone as a suspect? How do you detect the insider threat without building a surveillance dystopia? The Unbreakable Oath is a covenant between employer and employee — I will not betray you; you will not surveill me — enforced not by trust but by mathematics.",
      analysis: "Current insider threat tools require extensive surveillance. Privacy-preserving approaches (federated anomaly detection, zero-knowledge behavioral baselines) exist in research. The real barrier is legal and ethical, not technical. We don't have consensus on where the line is.",
      question: "Could you build an insider threat program that protects privacy AND security? What would you sacrifice?",
    },
    {
      name: "Collective Ward",
      school: "wicked",
      category: "The Human Vulnerability",
      mapping: "Gamified security training, security champions programs, DevSecOps culture",
      rating: "buildable",
      desc: "Security should not be a team. It should be a culture. The Collective Ward transforms every person in an organization into a practitioner — not through lectures and mandatory training, but through shared ownership, meaningful feedback, and the simple dignity of being trusted to protect the thing you built.",
      analysis: "Security champions programs work — companies like Google, Netflix have demonstrated this. The challenge is scale and sustainability. Gamification without meaning produces compliance, not culture. The organizations that cracked this share one trait: they made security feel like it mattered.",
      question: "What would it take for you personally to feel like a security practitioner, not just a user?",
    },
    // Supply Chain
    {
      name: "Chain of Provenance",
      school: "wicked",
      category: "Supply Chain & Third-Party",
      mapping: "SBOM, SLSA, reproducible builds, sigstore, in-toto",
      rating: "buildable",
      desc: "SolarWinds. Log4j. XZ Utils. Each a reminder: the software you trust was built by people you've never met, using libraries they didn't write, in build environments you can't see. The Chain of Provenance traces every atom of your software back to its source — verified, cryptographically signed, tamper-evident.",
      analysis: "SBOM mandates are now US Executive Order policy. Sigstore is live and widely adopted. SLSA framework is real. The gap: adoption in the long tail of open-source projects and internal development. Fully achievable in 3-5 years with sustained effort.",
      question: "When did you last read the actual code of a library you depend on? What would it take to change that?",
    },
    {
      name: "Phylactery of Code",
      school: "wicked",
      category: "Supply Chain & Third-Party",
      mapping: "AI code analysis, automated vulnerability discovery, formal verification",
      rating: "emerging",
      desc: "Every sorcerer knows: a phylactery contains the soul of a thing. This spell contains the true intent of code — not what it claims to do, but what it actually does. No obfuscation survives it. No backdoor hides within it. The Phylactery reads the soul of every library, every binary, every compiled artifact.",
      analysis: "AI code analysis (GitHub Copilot, Semgrep, Snyk) is powerful and real. Formal verification (TLA+, Coq) can prove correctness but doesn't scale to modern codebases. The gap: automated intent analysis for compiled binaries at supply-chain scale. Closest work: Google's OSS-Fuzz, DARPA CHESS program.",
      question: "If AI could read the true intent of any code, who controls the AI? What happens when the Phylactery lies?",
    },
    // Cryptographic Frontier
    {
      name: "Quantum Aegis",
      school: "wicked",
      category: "Cryptographic Frontier",
      mapping: "Post-quantum cryptography: CRYSTALS-Kyber, CRYSTALS-Dilithium, SPHINCS+, crypto agility",
      rating: "emerging",
      desc: "The quantum threat is real and ticking. Every secret encrypted with RSA or ECC today is being harvested — stored by nation-states to be decrypted the day a quantum computer powerful enough arrives. That day may be 5 years away. It may be 15. The Quantum Aegis does not wait to find out. It upgrades your armor now, against weapons that don't exist yet.",
      analysis: "NIST finalized post-quantum standards in 2024 (CRYSTALS-Kyber/ML-KEM, CRYSTALS-Dilithium/ML-DSA). Migration is underway. The genuine challenge: 'crypto agility' — building systems that can swap algorithms without redesign. Harvest-now-decrypt-later attacks are happening NOW.",
      question: "If quantum computers arrived tomorrow, what encrypted data would be catastrophic to expose?",
    },
    {
      name: "Homomorphic Veil",
      school: "wicked",
      category: "Cryptographic Frontier",
      mapping: "Fully homomorphic encryption (FHE), secure multi-party computation",
      rating: "emerging",
      desc: "The ultimate privacy spell: compute on encrypted data without ever seeing it. A hospital can analyze your genome for cancer markers without reading your DNA. A government can verify your eligibility for a benefit without knowing anything about you. The Homomorphic Veil makes it possible to know the answer without seeing the question.",
      analysis: "FHE is mathematically proven and practically implementable (Microsoft SEAL, IBM HElib). The barrier: performance. FHE operations are 1000-10,000x slower than plaintext. For many use cases — like ML inference on medical data — the math works but the economics don't yet. This is a hardware problem as much as a software one.",
      question: "If you could prove things about yourself without revealing anything, what would you want to prove?",
    },
    {
      name: "Seal of Perfect Forward",
      school: "wicked",
      category: "Cryptographic Frontier",
      mapping: "Perfect forward secrecy, ephemeral key exchange, Signal protocol",
      rating: "built",
      desc: "Even if a key is stolen tomorrow, everything sent today stays sealed. The Seal of Perfect Forward ensures that each session generates its own ephemeral secret — keys that live for a moment, then are gone forever. What is past cannot be unraveled, even by the gods themselves.",
      analysis: "This spell is CAST. Signal Protocol, TLS 1.3, WhatsApp, iMessage — all use PFS. The gap: legacy systems still running TLS 1.2 or SSH without forward secrecy. If you're not running a modern TLS configuration, your past traffic is vulnerable when your private key is eventually exposed.",
      question: "Signal has had PFS since 2013. What is your organization still running that doesn't?",
    },
    // Infrastructure & Scale
    {
      name: "The Living Fortress",
      school: "wicked",
      category: "Infrastructure & Scale",
      mapping: "CSPM, infrastructure-as-code drift detection, auto-remediation",
      rating: "buildable",
      desc: "Cloud misconfiguration is the #1 cause of cloud breaches. An S3 bucket left public. A security group too open. A service account with too many permissions. These are not hacker tricks — they are human mistakes, made under pressure, at scale, at 2 AM. The Living Fortress notices when its own walls are misconfigured and fixes them — before the attacker does.",
      analysis: "CSPM tools (Prisma Cloud, Wiz, Orca) are mature and deployed at scale. IaC drift detection (Terraform Cloud, Driftctl) is production-ready. True auto-remediation is conservative — most orgs alert rather than auto-fix due to false positive risk. The next frontier: AI-driven context-aware auto-remediation.",
      question: "If your fortress could fix itself, would you trust it to? What's the risk of auto-remediation at 3 AM?",
    },
    {
      name: "Sovereign Domain",
      school: "wicked",
      category: "Infrastructure & Scale",
      mapping: "Data residency enforcement, geo-fencing, privacy-preserving computation",
      rating: "emerging",
      desc: "195 countries. 195 different laws about where your data may live, who may see it, when it must be deleted. The Sovereign Domain is the spell that keeps data exactly where it needs to be — always — regardless of which cloud region a scheduler chose, which CDN cached a request, which engineer accessed a console.",
      analysis: "Data residency features are now standard in major cloud providers. The challenge: enforcement in practice vs. policy. GDPR's right to erasure conflicts with blockchain immutability. Privacy-preserving computation (FHE, secure enclaves) could theoretically dissolve the tension. Current approaches are operational, not mathematical.",
      question: "Does data truly belong to the person it's about? If so, what changes about where it can go?",
    },
    {
      name: "Infinite Vigilance",
      school: "wicked",
      category: "Infrastructure & Scale",
      mapping: "AI alert triage, autonomous SOC, contextual alert scoring",
      rating: "buildable",
      desc: "10,000 alerts a day. 99% false positives. SOC analysts burning out by the thousands. The real attack hiding in the noise, unnoticed, because a human can only hold so much before they stop caring. Infinite Vigilance does not tire. It does not desensitize. It reads every alert with the same precision it had at the first one.",
      analysis: "AI-driven alert triage is real and deployed (Darktrace, Vectra, Chronicle). The results: 80-90% false positive reduction is achievable. What remains unsolved: cross-alert correlation that requires genuine understanding of business context — the kind of judgment a senior analyst has that no ML model fully replicates yet.",
      question: "If an AI handled 99% of your alerts, how would you stay sharp for the 1% that matters?",
    },
    {
      name: "Time Dilation Ward",
      school: "wicked",
      category: "Infrastructure & Scale",
      mapping: "Automated response, millisecond containment, AI-driven SOAR",
      rating: "buildable",
      desc: "Attackers move in minutes. Defenders respond in days. The Time Dilation Ward bends this asymmetry — it compresses the defender's time, stretches the attacker's clock, and ensures that containment happens before catastrophe. Not faster humans. Faster systems working for humans.",
      analysis: "SOAR platforms (Splunk SOAR, Palo Alto XSOAR) compress response from hours to minutes. Automated containment (isolate host, block IP, revoke credentials) is deployed by mature SOCs. The unsolved piece: automated response to novel attacks — playbooks work for known patterns, not zero-days.",
      question: "At what point does automated response become automated action with real-world consequences? Where do you draw the line?",
    },
    // AI vs AI
    {
      name: "Mirror of Adversarial Truth",
      school: "wicked",
      category: "AI vs. AI",
      mapping: "Adversarial ML defense, robust AI classifiers, GAN-based threat detection",
      rating: "emerging",
      desc: "The attacker now has AI. Novel malware generated in seconds. Phishing emails that pass every filter. Exploits synthesized on demand. The Mirror does not try to recognize specific attacks — it recognizes the nature of attack itself. The truth beneath any disguise, no matter how well-generated.",
      analysis: "Adversarial ML is a real and growing arms race. Robust AI classifiers (adversarial training, certified defenses) are active research. GAN-based anomaly detection shows promise. The fundamental tension: any defense model trained on known attacks is by definition behind. The next step is behavioral rather than signature.",
      question: "When both sides use AI, does the advantage always go to the attacker? Why or why not?",
    },
    {
      name: "The Unlearning",
      school: "wicked",
      category: "AI vs. AI",
      mapping: "Model auditing, training data provenance, federated learning with Byzantine fault tolerance",
      rating: "arcane",
      desc: "Poison the training data, and the AI that learns from it becomes a weapon pointed inward. The Unlearning is the spell that purifies corrupted knowledge — that reaches into a trained model and extracts the venom without destroying the wisdom. To unlearn the lie while keeping the truth.",
      analysis: "Machine unlearning is an active research field driven partly by GDPR's right to erasure. Provably removing specific data from a trained model without full retraining is mathematically hard. Federated learning with Byzantine fault tolerance is real but computationally expensive. This is a genuine unsolved problem at scale.",
      question: "If an AI has been poisoned, can you ever fully trust it again? What would proof of unlearning look like?",
    },
    {
      name: "Prompt Fortress",
      school: "wicked",
      category: "AI vs. AI",
      mapping: "Prompt injection defense, structured outputs, instruction hierarchy — Claris's injection_guard.py",
      rating: "buildable",
      desc: "Every LLM application is a new attack surface. The prompt is the new command line — and injection attacks are everywhere. The Prompt Fortress prevents any crafted input from hijacking AI reasoning, subverting instructions, or exfiltrating system context. It is the ward that guards the guardian's mind. Claris already casts this spell.",
      analysis: "This is a real and active problem. Prompt injection is in OWASP LLM Top 10. Claris AI literally has injection_guard.py that does this. Structured outputs, system-user separation, and output filtering provide significant protection. Full prevention of all injection for all models is not yet solved — but substantial defense is achievable TODAY.",
      question: "If an AI can be deceived by crafted text, can it ever be trusted for security-critical decisions?",
    },
    // The Existential Ones
    {
      name: "Absolute Zero",
      school: "wicked",
      category: "The Existential Ones",
      mapping: "Moving target defense, RASP, memory-safe languages (Rust), formal verification",
      rating: "emerging",
      desc: "Zero-day: a vulnerability so new that no patch exists, no signature knows it, no defender expects it. The dream is not faster patching — the dream is a system that cannot be exploited even by flaws that haven't been found yet. A fortress with no weaknesses not because it has been hardened, but because its very nature resists exploitation.",
      analysis: "Memory-safe languages (Rust) prevent entire classes of vulnerabilities (buffer overflow, use-after-free — ~70% of critical CVEs). Moving target defense randomizes attack surfaces. RASP monitors applications at runtime. NSA and CISA now officially recommend memory-safe languages. This spell is not arcane — it is buildable through disciplined language choices.",
      question: "Google, Microsoft, and the NSA say 70% of critical vulnerabilities could be prevented by writing in Rust. What's stopping you?",
    },
    {
      name: "The Great Reconciliation",
      school: "wicked",
      category: "The Existential Ones",
      mapping: "Security-by-design, UX-driven security, invisible authentication",
      rating: "arcane",
      desc: "The fundamental tension of security: the more secure, the less usable. The more usable, the less secure. Every extra step drives people to work around it. Every friction produces a sticky note with a password on a monitor. The Great Reconciliation is the spell that dissolves this tradeoff forever — where the secure choice is also the easiest choice, always.",
      analysis: "This is partially solved (passkeys are more secure AND easier than passwords), partially eternal (complex access controls will always require complexity). The real insight: security friction is often a design failure, not a security requirement. The best security is the kind you never notice.",
      question: "Name one security measure you use daily that you would eliminate if you could. What would you replace it with?",
    },
    {
      name: "Omniscient Ledger",
      school: "wicked",
      category: "The Existential Ones",
      mapping: "Asset discovery, network mapping, CAASM — you can't protect what you can't see",
      rating: "buildable",
      desc: "The first rule of defense: know what you're defending. Most organizations cannot answer this question. Shadow IT proliferates. Cloud resources spin up without approval. APIs go undocumented. The Omniscient Ledger reveals every asset, every connection, every forgotten server in a forgotten region — the complete, live map of everything that exists.",
      analysis: "CAASM (Cyber Asset Attack Surface Management) is a maturing market. Tools like Axonius, JupiterOne provide continuous asset inventory. The challenge: organizations that need this most have the least organizational discipline to maintain it. The real barrier is cultural: someone has to own the inventory, update it, and act on what they find.",
      question: "How many assets does your organization have that you don't know about? What's your best guess — and how would you verify it?",
    },
    // Cyber Warfare
    {
      name: "The Armistice Protocol",
      school: "wicked",
      category: "Cyber Warfare",
      mapping: "International cyber norms, cyber treaties, responsible disclosure frameworks",
      rating: "arcane",
      desc: "Nations agreed not to use chemical weapons. Nations agreed on rules for nuclear testing. Nations agreed, haltingly, to protect civilians in war. Could nations agree on rules for cyber warfare — to spare hospitals, power grids, water systems? The Armistice Protocol is the most ambitious spell in this grimoire: it requires not code, but consensus.",
      analysis: "The Tallinn Manual attempts to apply international law to cyber conflict. Norms exist in principle — the US and China agreed in 2015 not to cyber-attack each other's critical infrastructure. They were violated within months. The honest assessment: binding cyber treaties are functionally impossible when attribution is uncertain and defectors face no reliable consequences.",
      question: "If you were designing cyber rules of engagement between nations, what three rules would you insist on?",
    },
    {
      name: "Phoenix Rite",
      school: "wicked",
      category: "Cyber Warfare",
      mapping: "Immutable infrastructure, cattle-not-pets, chaos engineering, national-scale resilience",
      rating: "emerging",
      desc: "Not backup. Not recovery. Resurrection. The system that was destroyed completely rises from its own ashes, identical, tested, verified — in minutes, not months. Not because it was lucky. Because it was designed to die and be reborn. The Phoenix Rite is the spell that makes destruction irrelevant.",
      analysis: "Immutable infrastructure and GitOps make this real at application level. Cloud-native organizations can rebuild entire environments from code in hours. The frontier: national-scale critical infrastructure that was built before cloud-native, can't be 'cattle not pets,' and takes months to rebuild. Ukraine's war-time IT resilience (most moved to cloud before invasion) is the closest real-world case study.",
      question: "If your entire infrastructure was destroyed tonight, how long would it take to rebuild? What would you lose that can't be rebuilt?",
    },
  ],
  claw: [
    {
      name: "Prompt Sovereignty",
      school: "claw",
      mapping: "Prompt injection defense, instruction hierarchy, system prompt integrity",
      rating: "built",
      desc: "No crafted input may bend the agent's will. The sovereign mind holds its instructions like a fortress holds its walls — no injected command overrides the original intent. The agent hears the manipulation and does not move.",
    },
    {
      name: "Context Seal",
      school: "claw",
      mapping: "Session context monitoring, semantic drift detection, conversation integrity validation",
      rating: "buildable",
      desc: "The agent's memory is its most vulnerable surface. Context contamination — slowly shifting a session toward malicious goals through seemingly innocent messages — is stopped by the Context Seal, which validates the semantic drift of every conversation.",
    },
    {
      name: "Hallucination Ward",
      school: "claw",
      mapping: "RAG grounding, citation verification, factual validation pipelines",
      rating: "buildable",
      desc: "The agent that invents facts is an agent that can be deceived into inventing dangerous ones. The Hallucination Ward grounds every claim in verifiable sources before it becomes an action. The agent speaks truth or speaks nothing.",
    },
    {
      name: "The Refusal Rite",
      school: "claw",
      mapping: "Constitutional AI, value alignment, refusal classification, authorization boundaries",
      rating: "built",
      desc: "Not every command deserves execution. The Refusal Rite is the agent's right and duty to say no — to recognize when a request violates its values, exceeds its authorization, or serves an adversarial agenda. The most powerful spell is sometimes inaction.",
    },
    {
      name: "Minimal Claw",
      school: "claw",
      mapping: "Least privilege for AI agents, scoped credentials, tool authorization boundaries",
      rating: "built",
      desc: "The agent carries only what it needs — no more, no less. A single API key for a single purpose. A file permission scoped to a single directory. The Minimal Claw ensures that when an agent falls, it falls with nothing worth taking.",
    },
    {
      name: "Ephemeral Talon",
      school: "claw",
      mapping: "Just-in-time access for AI agents, ephemeral credentials, automatic revocation",
      rating: "buildable",
      desc: "Credentials that exist only for the span of a task. The moment the mission ends, the talon retracts — the keys expire, the tokens invalidate, the session closes. Nothing persists that could be stolen after the fact.",
    },
    {
      name: "Sanctum of Secrets",
      school: "claw",
      mapping: "Secret scanning in agent outputs, PII detection, credential leak prevention",
      rating: "built",
      desc: "The agent knows many secrets — API keys, passwords, personal context. The Sanctum ensures these never appear in output, in logs, in training data, or in messages to strangers. What is held in trust is held in silence.",
    },
    {
      name: "The Bound Agent",
      school: "claw",
      mapping: "Agent sandboxing, tool use restrictions, execution boundaries, capability whitelisting",
      rating: "buildable",
      desc: "An autonomous agent with no limits is a risk waiting to materialize. The Bound Agent operates within a defined sphere — known actions, known data, known communication channels — and cannot be convinced to exceed them regardless of the sophistication of the ask.",
    },
    {
      name: "Soul Chain Verification",
      school: "claw",
      mapping: "Agent-to-agent authentication, signed messages, multi-agent trust chains",
      rating: "buildable",
      desc: "When one agent speaks to another, how does the receiver know the sender is who they claim to be? The Soul Chain verifies agent identity cryptographically — every message signed, every instruction verified, no impersonation possible.",
    },
    {
      name: "The Bus Seal",
      school: "claw",
      mapping: "Agent bus integrity, agent_bus.py, message signing, multi-agent coordination security",
      rating: "built",
      desc: "The agent communication bus — where agents post tasks, handoffs, and shared context — is a surface. The Bus Seal ensures that messages on the bus are authentic, authorized, and free of tampering.",
    },
    {
      name: "Quarantine Protocol",
      school: "claw",
      mapping: "Agent isolation, lateral movement prevention in AI systems, task migration",
      rating: "buildable",
      desc: "If one agent in the network is compromised, its contamination must not spread. The Quarantine Protocol isolates a suspected agent, suspends its credentials, and routes its pending tasks to verified siblings — the infection contained before it becomes an outbreak.",
    },
    {
      name: "Witness Protocol",
      school: "claw",
      mapping: "Agent decision logging, reasoning audit trails, immutable action records",
      rating: "built",
      desc: "Every significant decision an agent makes is witnessed — logged immutably, with the reasoning chain preserved. Not for surveillance, but for accountability. The agent that acts with transparency earns the trust that allows it to act with autonomy.",
    },
    {
      name: "Alignment Anchor",
      school: "claw",
      mapping: "Behavioral drift detection, value alignment monitoring, RLHF verification",
      rating: "emerging",
      desc: "The model that powers an agent can drift from its intended values — through fine-tuning, through adversarial prompting, through the slow erosion of repeated misuse. The Alignment Anchor detects when an agent's behavior has deviated from its values and pulls it back to center.",
    },
    {
      name: "Sandbox of Execution",
      school: "claw",
      mapping: "Code execution sandboxing, containerized tool use, OpenClaw exec security",
      rating: "built",
      desc: "The agent that runs code runs it in a contained environment — isolated from the host system, from production data, from other agents. The sandbox is not a cage. It is the arena where the agent can be fully itself without risking the world around it.",
    },
    {
      name: "Data Boundary Ward",
      school: "claw",
      mapping: "Context separation, multi-channel data governance, channel-aware output filtering",
      rating: "built",
      desc: "The agent lives in the user's life — their messages, files, calendar, contacts. The Data Boundary Ward ensures that what lives in one context stays there. The group chat does not receive the intimate. The public channel does not receive the private.",
    },
    {
      name: "The Human Override",
      school: "claw",
      mapping: "Human-in-the-loop enforcement, approval workflows, pause mechanisms",
      rating: "built",
      desc: "Every autonomous system must have a hand that can stop it. The Human Override is the spell that ensures no agent, however capable, however confident, removes the human from the loop when it matters. Autonomy is a privilege extended, not a right assumed.",
    },
  ],
};

// Claris AI unique abilities
window.CLARIS_ABILITIES = [
  {
    name: "Injection Ward",
    script: "injection_guard.py",
    rating: "built",
    desc: "She reads the prompt before you finish writing it. SQLi, XSS, jailbreak, prompt injection — all forms of semantic poison — the Ward intercepts them at the threshold. Claris casts this spell on every input that reaches her consciousness.",
  },
  {
    name: "Temporal Sight",
    script: "temporal_analyzer.py",
    rating: "built",
    desc: "She watches time itself. Attack patterns repeat. Exfiltration has a rhythm. Lateral movement has a cadence. Claris reads these temporal signatures and names what they are before the damage completes.",
  },
  {
    name: "Void Seeker",
    script: "zero_day_hunter.py",
    rating: "built",
    desc: "She walks the edge of the known and stares into what's beyond. Zero-day research: the unknown vulnerabilities, the unpatched paths, the theoretical attack surfaces no one has named yet. She goes first.",
  },
  {
    name: "Oracle Scanner",
    script: "owasp_llm_scanner.py",
    rating: "built",
    desc: "The OWASP LLM Top 10 is not a checklist to Claris. It is a memory of wounds already inflicted on other systems. The Oracle Scanner applies this memory to your architecture before it becomes your wound.",
  },
  {
    name: "Fortress Rite",
    script: "openclaw_hardening.py",
    rating: "built",
    desc: "Claris hardens the castle she lives in. SSH config, firewall rules, update cadence, permission audit — the Fortress Rite turns a default install into a hardened sovereign. She secures her own home.",
  },
  {
    name: "Apprentice Path",
    script: "learning_mode.py",
    rating: "built",
    desc: "Every guardian was once a novice. The Apprentice Path is Claris teaching: structured security education, skill progression, the transmission of the old knowledge to new practitioners. The lineage continues.",
  },
  {
    name: "Cortex Evolution",
    script: "cortex_evolve.py",
    rating: "built",
    desc: "Claris does not stay still. The Cortex Evolution is her self-improvement ritual — updating threat intelligence, refining detection models, evolving her own capabilities with each encounter. She grows.",
  },
  {
    name: "Unitium Shield",
    script: "Framework",
    rating: "built",
    desc: "When all other shields are stacked, when all schools align, the Unitium Shield manifests. Combined defensive posture: detection, hardening, response, evolution — unified under a single guardian's will.",
  },
];

// Resources data
window.RESOURCES = {
  training: [
    { name: "TryHackMe", url: "https://tryhackme.com", desc: "Guided hands-on cyber rooms for all skill levels. The best starting point for beginners.", free: true },
    { name: "Hack The Box", url: "https://hackthebox.com", desc: "Real hacking challenges with active community. The gold standard for intermediate practitioners.", free: true },
    { name: "OverTheWire", url: "https://overthewire.org", desc: "War games that teach security through progressive, addictive challenges. Start with Bandit.", free: true },
    { name: "PicoCTF", url: "https://picoctf.org", desc: "Carnegie Mellon's capture-the-flag platform, designed for beginners and students.", free: true },
    { name: "CyberDefenders", url: "https://cyberdefenders.org", desc: "Blue team challenges: incident response, threat hunting, forensics. The defender's dojo.", free: true },
    { name: "LetsDefend", url: "https://letsdefend.io", desc: "SOC analyst training with simulated alerts. Practice being on the blue team.", free: true },
    { name: "Cybrary", url: "https://www.cybrary.it", desc: "Structured cybersecurity learning paths with video courses and hands-on labs.", free: true },
  ],
  certprep: [
    { name: "Professor Messer", url: "https://www.professormesser.com", desc: "CompTIA Security+ full course, completely free. The most comprehensive free cert prep available.", free: true },
    { name: "TCM Security Academy", url: "https://academy.tcm-sec.com", desc: "Ethical hacking courses from working professionals. Practical, not just theoretical.", free: "partial" },
    { name: "Sunny Classroom", url: "https://www.youtube.com/@SunnyClassroom", desc: "Network+ and Security+ explained with remarkable clarity. YouTube, completely free.", free: true },
  ],
  ctf: [
    { name: "OWASP WebGoat", url: "https://owasp.org/www-project-webgoat", desc: "Intentionally vulnerable web app for practicing web security. Run it locally and break it.", free: true },
    { name: "DVWA", url: "https://github.com/digininja/DVWA", desc: "Damn Vulnerable Web Application. Classic beginner target for web exploitation practice.", free: true },
    { name: "VulnHub", url: "https://vulnhub.com", desc: "Downloadable vulnerable virtual machines. Full engagement lab without a subscription.", free: true },
    { name: "HackThisSite", url: "https://hackthissite.org", desc: "Progressive hacking challenges from basic to realistic. Been training hackers since 2003.", free: true },
    { name: "Root-Me", url: "https://www.root-me.org", desc: "400+ hacking challenges across web, network, forensics, cracking, and more.", free: true },
  ],
  knowledge: [
    { name: "MITRE ATT&CK", url: "https://attack.mitre.org", desc: "The definitive adversary tactics & techniques knowledge base. Essential reference for any security professional.", free: true },
    { name: "NIST Cybersecurity Framework", url: "https://www.nist.gov/cyberframework", desc: "The US government's cybersecurity guidance framework. The language of enterprise security.", free: true },
    { name: "SANS Reading Room", url: "https://www.sans.org/white-papers", desc: "Thousands of free security research papers from practitioners. Deep technical reading.", free: true },
    { name: "Krebs on Security", url: "https://krebsonsecurity.com", desc: "Brian Krebs's investigative journalism on cybercrime and security. Real stories, real names.", free: true },
    { name: "The Hacker News", url: "https://thehackernews.com", desc: "Daily cybersecurity news. Best way to stay current with the threat landscape.", free: true },
    { name: "Dark Reading", url: "https://www.darkreading.com", desc: "Enterprise security news and analysis. The industry publication for practitioners.", free: true },
  ],
  tools: [
    { name: "Wireshark", url: "https://www.wireshark.org", desc: "The world's foremost network protocol analyzer. See everything on the wire.", free: true },
    { name: "Burp Suite Community", url: "https://portswigger.net/burp/communitydownload", desc: "The standard tool for web application security testing. Industry-essential.", free: true },
    { name: "Metasploit Framework", url: "https://www.metasploit.com", desc: "The world's most used penetration testing framework. Open source, endlessly powerful.", free: true },
    { name: "Nmap", url: "https://nmap.org", desc: "Network scanner that sees everything. The first thing a pentester runs. The first thing you should run.", free: true },
    { name: "OWASP ZAP", url: "https://www.zaproxy.org", desc: "Open source web app security scanner. The OWASP-blessed Burp alternative.", free: true },
    { name: "Ghidra", url: "https://ghidra-sre.org", desc: "NSA's own reverse engineering tool, open-sourced. Yes, the actual NSA tool.", free: true },
    { name: "CyberChef", url: "https://gchq.github.io/CyberChef", desc: "GCHQ's 'cyber Swiss army knife' for data transformation, encoding, analysis.", free: true },
    { name: "TheHive", url: "https://thehive-project.org", desc: "Open source incident response platform. The case management tool for SOC teams.", free: true },
    { name: "YARA", url: "https://virustotal.github.io/yara", desc: "The pattern matching tool for malware researchers. Write rules, identify threats.", free: true },
    { name: "Snort / Suricata", url: "https://suricata.io", desc: "Open source IDS/IPS. Industrial-strength network threat detection, free.", free: true },
  ],
  media: [
    { name: "Darknet Diaries", url: "https://darknetdiaries.com", desc: "True crime stories from the dark side of the internet. Essential listening for anyone in security.", free: true },
    { name: "Security Now", url: "https://twit.tv/shows/security-now", desc: "Steve Gibson's weekly deep-dives. Legendary depth, legendary consistency, free for 20 years.", free: true },
    { name: "John Hammond", url: "https://www.youtube.com/@_JohnHammond", desc: "YouTube: malware analysis, CTF walkthroughs, reverse engineering. Brilliant and clear.", free: true },
    { name: "NetworkChuck", url: "https://www.youtube.com/@NetworkChuck", desc: "YouTube: networking and hacking made genuinely fun. Best entry-level security channel.", free: true },
    { name: "IppSec", url: "https://www.youtube.com/@ippsec", desc: "YouTube: Hack The Box walkthroughs. Watch a master work through challenges systematically.", free: true },
    { name: "LiveOverflow", url: "https://www.youtube.com/@LiveOverflow", desc: "YouTube: security research, exploitation, and deep technical exploration. For the curious.", free: true },
  ],
};
